/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import static Admin.AdminFrame.WriteProfessor;
import static JavaApp.LogInFrame.counterProfessorAdmin;
import static JavaApp.LogInFrame.professorAdmin;
import static JavaApp.LogInFrame.returnCounterProfessor;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Samardzija Njegos
 */
public class AddProfessor extends javax.swing.JFrame {

    /**
     * Creates new form AddProfessor
     */
    public AddProfessor() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        errTextID.setText(" ");
        errTextName.setText(" ");
        errTextUsername.setText(" ");
        errTextPass.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newJPanel1 = new AddOns.TransparentPanel();
        addProfessorLabel = new javax.swing.JLabel();
        exit = new AddOns.ProfilePicture();
        addProfessorBtn = new AddOns.MyButton();
        professorIDTextField = new javax.swing.JTextField();
        professorNameTextField = new javax.swing.JTextField();
        professorUsernameTextField = new javax.swing.JTextField();
        professorPassTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errTextID = new javax.swing.JLabel();
        errTextName = new javax.swing.JLabel();
        errTextUsername = new javax.swing.JLabel();
        errTextPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        newJPanel1.setBackground(new java.awt.Color(87, 87, 87));

        addProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addProfessorLabel.setForeground(new java.awt.Color(255, 255, 255));
        addProfessorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addProfessorLabel.setText("Add Professor");

        exit.setBackground(new java.awt.Color(67, 67, 67));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/turn-off.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        addProfessorBtn.setText("Add professor");
        addProfessorBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addProfessorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfessorBtnActionPerformed(evt);
            }
        });

        professorIDTextField.setBackground(new java.awt.Color(87, 87, 87));
        professorIDTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        professorIDTextField.setForeground(new java.awt.Color(255, 255, 255));
        professorIDTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        professorIDTextField.setSelectedTextColor(new java.awt.Color(87, 87, 87));
        professorIDTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        professorIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorIDTextFieldActionPerformed(evt);
            }
        });

        professorNameTextField.setBackground(new java.awt.Color(87, 87, 87));
        professorNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        professorNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        professorNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        professorNameTextField.setSelectedTextColor(new java.awt.Color(87, 87, 87));
        professorNameTextField.setSelectionColor(new java.awt.Color(255, 255, 255));

        professorUsernameTextField.setBackground(new java.awt.Color(87, 87, 87));
        professorUsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        professorUsernameTextField.setForeground(new java.awt.Color(255, 255, 255));
        professorUsernameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        professorUsernameTextField.setSelectedTextColor(new java.awt.Color(87, 87, 87));
        professorUsernameTextField.setSelectionColor(new java.awt.Color(255, 255, 255));

        professorPassTextField.setBackground(new java.awt.Color(87, 87, 87));
        professorPassTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        professorPassTextField.setForeground(new java.awt.Color(255, 255, 255));
        professorPassTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        professorPassTextField.setSelectedTextColor(new java.awt.Color(87, 87, 87));
        professorPassTextField.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Professor ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Professor full name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Professor username:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Professor password:");

        errTextID.setForeground(java.awt.Color.red);
        errTextID.setText("ID already exist!");

        errTextName.setForeground(java.awt.Color.red);
        errTextName.setText("Name not entered correctly!");

        errTextUsername.setForeground(java.awt.Color.red);
        errTextUsername.setText("jLabel8");

        errTextPass.setForeground(java.awt.Color.red);
        errTextPass.setText("jLabel9");

        javax.swing.GroupLayout newJPanel1Layout = new javax.swing.GroupLayout(newJPanel1);
        newJPanel1.setLayout(newJPanel1Layout);
        newJPanel1Layout.setHorizontalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProfessorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(newJPanel1Layout.createSequentialGroup()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(professorIDTextField)
                    .addComponent(professorNameTextField)
                    .addComponent(professorUsernameTextField)
                    .addComponent(professorPassTextField))
                .addContainerGap())
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newJPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(newJPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addProfessorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errTextID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errTextName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errTextUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errTextPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        newJPanel1Layout.setVerticalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProfessorLabel)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errTextID)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errTextName)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errTextUsername)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errTextPass)
                .addGap(17, 17, 17)
                .addComponent(addProfessorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void addProfessorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfessorBtnActionPerformed
        String id = professorIDTextField.getText();
        String name = professorNameTextField.getText().trim();
        String username = professorUsernameTextField.getText();
        String password = professorPassTextField.getText();
        byte[] data = null;
        BufferedImage bImage = null;
        boolean found = false;

        errTextID.setText(" ");
        errTextName.setText(" ");
        errTextUsername.setText(" ");
        errTextPass.setText(" ");

        try {
            bImage = ImageIO.read(getClass().getResource("/Icons/user.png"));
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            ImageIO.write(bImage, "png", bos);
            data = bos.toByteArray();
        } catch (IOException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (id.isEmpty()) {
            found = true;
            errTextID.setText("ID not entered!");
        }
        if (username.isEmpty()) {
            found = true;
            errTextUsername.setText("Username not entered!");
        }

        if (name.isEmpty()) {
            found = true;
            errTextName.setText("Name not entered!");
        }
        if (!name.contains(" ")) {
            found = true;
            errTextName.setText("Name not entered correctly!");
        }
        if (password.isEmpty() || password.equals(" ")) {
            found = true;
            errTextPass.setText("Password not entered!");
        }

        for (int i = 0; i < counterProfessorAdmin; i++) {
            if (professorAdmin[i].getID().equals(id)) {
                found = true;
                errTextID.setText("ID alredy exists!");
            }
            if (professorAdmin[i].getUsername().equals(username)) {
                found = true;
                errTextUsername.setText("Username already exists!");
            }
        }

        if (found == false) {
            professorAdmin[counterProfessorAdmin] = new Professor();
            professorAdmin[counterProfessorAdmin].setID(id);
            professorAdmin[counterProfessorAdmin].setName(name);
            professorAdmin[counterProfessorAdmin].setUsername(username);
            professorAdmin[counterProfessorAdmin].setPassword(password);
            professorAdmin[counterProfessorAdmin].setPicture(data);

            counterProfessorAdmin++;

            returnCounterProfessor(counterProfessorAdmin);

            WriteProfessor();
            dispose();
        }
    }//GEN-LAST:event_addProfessorBtnActionPerformed

    private void professorIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AddOns.MyButton addProfessorBtn;
    private javax.swing.JLabel addProfessorLabel;
    private javax.swing.JLabel errTextID;
    private javax.swing.JLabel errTextName;
    private javax.swing.JLabel errTextPass;
    private javax.swing.JLabel errTextUsername;
    private AddOns.ProfilePicture exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private AddOns.TransparentPanel newJPanel1;
    private javax.swing.JTextField professorIDTextField;
    private javax.swing.JTextField professorNameTextField;
    private javax.swing.JTextField professorPassTextField;
    private javax.swing.JTextField professorUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
