/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApp;

import static JavaApp.LogInFrame.arrayObligationType;
import static JavaApp.LogInFrame.arrayObligations;
import static JavaApp.LogInFrame.counterObligationType;
import static JavaApp.MainFrame.changeObligationCounter;
import static JavaApp.MainFrame.listModel;
import static JavaApp.MainFrame.studentList2;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samardzija Njegos
 */
public class AddObligation extends javax.swing.JFrame {

    /**
     * Creates new form AddObligation
     */
    DefaultTableModel modelTemp;
    JTable table;
    String subjectName;
    int counterObligations;
    int newCounter;
    Student students[];
    int studentCounter;

    public void pass(String[] typeOfObligation, int counterTypeOfObligation, String nameOfSubject, int obligationsCounter, Student[] studentsArray, int studentsCounter) {

        students = studentsArray;
        studentCounter = studentsCounter;
        subjectName = nameOfSubject;
        counterObligations = obligationsCounter;
        for (int i = 0; i < counterTypeOfObligation; i += 2) {
            ObligationType.addItem(typeOfObligation[i]);
        }
    }

    public AddObligation() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newJPanel1 = new AddOns.TransparentPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ObligationType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ObligationNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MaximumPointsText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        myButton1 = new AddOns.MyButton();
        profilePicture3 = new AddOns.ProfilePicture();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        newJPanel1.setBackground(new java.awt.Color(67, 67, 67));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Obligation");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Obligation Type:");

        ObligationType.setBackground(java.awt.Color.black);
        ObligationType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ObligationType.setForeground(new java.awt.Color(255, 255, 255));
        ObligationType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(214, 0, 255)));
        ObligationType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ObligationType.setFocusable(false);
        ObligationType.setRequestFocusEnabled(false);
        ObligationType.setVerifyInputWhenFocusTarget(false);
        ObligationType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObligationTypeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Obligation Name:");

        ObligationNameText.setBackground(new java.awt.Color(67, 67, 67));
        ObligationNameText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ObligationNameText.setForeground(new java.awt.Color(255, 255, 255));
        ObligationNameText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(214, 0, 255)));
        ObligationNameText.setSelectedTextColor(new java.awt.Color(214, 0, 255));
        ObligationNameText.setSelectionColor(new java.awt.Color(255, 255, 255));
        ObligationNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObligationNameTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maximum Points:");

        MaximumPointsText.setBackground(new java.awt.Color(67, 67, 67));
        MaximumPointsText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MaximumPointsText.setForeground(new java.awt.Color(255, 255, 255));
        MaximumPointsText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(214, 0, 255)));
        MaximumPointsText.setSelectedTextColor(new java.awt.Color(214, 0, 255));
        MaximumPointsText.setSelectionColor(new java.awt.Color(255, 255, 255));
        MaximumPointsText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MaximumPointsTextKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" ");
        jLabel6.setToolTipText("");

        myButton1.setText("Add");
        myButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        profilePicture3.setBackground(new java.awt.Color(67, 67, 67));
        profilePicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/turn-off.png"))); // NOI18N
        profilePicture3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePicture3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout newJPanel1Layout = new javax.swing.GroupLayout(newJPanel1);
        newJPanel1.setLayout(newJPanel1Layout);
        newJPanel1Layout.setHorizontalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newJPanel1Layout.createSequentialGroup()
                        .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newJPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaximumPointsText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(newJPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(profilePicture3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(newJPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ObligationType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ObligationNameText)
                            .addGroup(newJPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newJPanel1Layout.setVerticalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(profilePicture3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObligationType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObligationNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaximumPointsText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newJPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ObligationNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObligationNameTextActionPerformed

    }//GEN-LAST:event_ObligationNameTextActionPerformed

    private void ObligationTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObligationTypeMouseClicked

    }//GEN-LAST:event_ObligationTypeMouseClicked

    private void MaximumPointsTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaximumPointsTextKeyTyped
        char enteredChar = evt.getKeyChar();

        if (!Character.isDigit(enteredChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_MaximumPointsTextKeyTyped

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed

        String temp2 = String.valueOf(ObligationType.getSelectedItem());
        String temp3 = ObligationNameText.getText();
        String temp4 = MaximumPointsText.getText();

        if ("".equals(temp4) || temp4 == null || "".equals(temp3) || temp3 == null) {

            jLabel6.setText("Parameters not entered!");
            jLabel6.setVisible(true);
        } else {
            if (studentCounter == 0) {
                studentCounter = 1;
            }
            newCounter = counterObligations + studentCounter;
            for (int i = counterObligations, j = 0; i < newCounter; i++, j++) {
                arrayObligations[i] = new Obligations();
                arrayObligations[i].setStudentName(students[j].getName());
                arrayObligations[i].setStudentID(students[j].getId());
                arrayObligations[i].setSubjectName(subjectName);
                arrayObligations[i].setObligationName(temp3);
                arrayObligations[i].setObligationType(temp2);
                arrayObligations[i].setMaximumPoints(Integer.parseInt(temp4));
                arrayObligations[i].setScoredPoints(0);
            }
            counterObligations = newCounter;
            changeObligationCounter(counterObligations);
            //writeTableProfessorObligations(temp2 + "  -  " + temp3);
            //DisableBtns();

            arrayObligationType[counterObligationType] = temp2 + "  -  " + temp3;
            counterObligationType++;

            listModel.removeAllElements();
            for (int i = 0; i < counterObligationType; i++) {
                listModel.addElement(arrayObligationType[i]);
            }
            studentList2.setModel(listModel);
            dispose();
        }

    }//GEN-LAST:event_myButton1ActionPerformed

    private void profilePicture3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePicture3MouseClicked
        dispose();
    }//GEN-LAST:event_profilePicture3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddObligation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddObligation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddObligation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddObligation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddObligation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MaximumPointsText;
    private javax.swing.JTextField ObligationNameText;
    private javax.swing.JComboBox<String> ObligationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private AddOns.MyButton myButton1;
    private AddOns.TransparentPanel newJPanel1;
    private AddOns.ProfilePicture profilePicture3;
    // End of variables declaration//GEN-END:variables
}
